import React from "react";
export const Search = () => <div data-testid="search-icon" />;
export const AlertCircle = () => <div data-testid="alert-icon" />;
export const CheckCircle = () => <div data-testid="check-icon" />;
export const ArrowLeft = () => <div data-testid="arrow-left-icon" />;
export const ArrowUp = () => <div data-testid="arrow-up-icon" />;
export const ArrowDown = () => <div data-testid="arrow-down-icon" />;
export const Sparkles = () => <div data-testid="sparkles-icon" />;
export const MessageSquare = () => <div data-testid="message-square-icon" />;
export const X = () => <div data-testid="x-icon" />;
